name = "LMD4MLTraining"
uuid = "916db72f-d5ae-442a-ab7c-396ee51ba326"
version = "1.0.0-DEV"
authors = ["Group"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Bonito = "4.1.11"
Dates = "1.11.0"
Flux = "0.16.5"
Logging = "1.11"
MLDatasets = "0.5.13"
Makie = "0.24.8"
Sockets = "1.11.0"
Statistics = "1.11.1"
WGLMakie = "0.13.8"
Zygote = "0.7.10"
julia = "1.11"
Aqua = "0.8"
Test = "1"
Profile = "1"
BenchmarkTools = "1.6.3"
Distributed = "1.11.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test","Aqua"]
dev = ["Profile","BenchmarkTools"]